from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from pathlib import Path

from .config import (
    DEFAULT_CHART_PATH,
    DEFAULT_CONFIG_DIR,
    DEFAULT_CONFIG_FILE,
    DEFAULT_DATA_DIR,
    DEFAULT_DB_PATH,
    DEFAULT_FULL_REPORT_SCHEDULE,
    DEFAULT_SPEEDTEST_MINUTES,
    validate_webhook_url,
)


SERVICE_TEMPLATE = """[Unit]
Description=Pi Probe Discord {mode_label}
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory={install_dir}
ExecStart={service_command} {mode}
"""


TIMER_TEMPLATE = """[Unit]
Description={description}

[Timer]
{schedule_line}
RandomizedDelaySec={random_delay}
Persistent=true
Unit={unit_name}.service

[Install]
WantedBy=timers.target
"""


TIMER_OVERRIDE_TEMPLATE = """[Timer]
OnBootSec=
OnActiveSec=
OnUnitActiveSec=
OnCalendar=
RandomizedDelaySec=
OnBootSec={on_boot}
OnActiveSec={on_active}
{schedule_line}
RandomizedDelaySec={random_delay}
"""


ENV_TEMPLATE = """# Generated by pi-probe-discord installer
WEBHOOK_URL="{webhook_url}"
DB_PATH="{db_path}"
CHART_FILE="{chart_path}"
LOG_FILE="/tmp/pihole-update-discord.log"
HISTORY_RETENTION_DAYS="365"
MAX_TEXT_FIELD_LENGTH="1200"
REQUEST_TIMEOUT="30"
SPEEDTEST_SCHEDULE_MINUTES="{speedtest_minutes}"
FULL_REPORT_SCHEDULE="{full_report_schedule}"
"""

CRON_KEYWORDS = [
    "pihole_update_report.py",
    "pihole-update-discord",
    "webhook",
    "discord.com/api/webhooks",
]

SYSTEMD_UNIT_HINTS = [
    "pi-probe-discord",
    "pi-probe",
    "pihole-update",
    "speedtest",
    "discord",
]


def _prompt(text: str, default: str) -> str:
    raw = input(f"{text} [{default}]: ").strip()
    return raw or default


def _prompt_yes_no(text: str, default: bool = True) -> bool:
    default_label = "Y/n" if default else "y/N"
    raw = input(f"{text} [{default_label}]: ").strip().lower()
    if not raw:
        return default
    return raw in {"y", "yes"}


def _prompt_webhook(default: str) -> str:
    while True:
        value = _prompt("Discord webhook URL", default)
        try:
            return validate_webhook_url(value)
        except RuntimeError as exc:
            print(f"Invalid webhook URL: {exc}")


def _validate_hhmm(value: str) -> str:
    parts = value.split(":")
    if len(parts) != 2:
        raise ValueError("Expected time in HH:MM format")
    hour = int(parts[0])
    minute = int(parts[1])
    if hour < 0 or hour > 23 or minute < 0 or minute > 59:
        raise ValueError("Time must be a valid 24-hour HH:MM value")
    return f"{hour:02d}:{minute:02d}"


def _run_capture(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, text=True, capture_output=True, check=False)


def _matching_cron_lines(lines: list[str]) -> list[str]:
    matches: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lowered = stripped.lower()
        if any(keyword in lowered for keyword in CRON_KEYWORDS):
            matches.append(line)
    return matches


def _inspect_and_clean_user_crontab() -> list[str]:
    if shutil.which("crontab") is None:
        return []

    result = _run_capture(["crontab", "-l"])
    if result.returncode != 0 and "no crontab" in (result.stderr or "").lower():
        return []
    if result.returncode != 0:
        print("Could not inspect current user crontab.")
        return []

    lines = result.stdout.splitlines()
    matches = _matching_cron_lines(lines)
    if not matches:
        return []

    print("Found existing cron entries that may overlap with this application:")
    for entry in matches:
        print(f"  {entry}")

    if not _prompt_yes_no("Preview cleanup plan for these cron entries?", default=True):
        return matches

    print("Proposed cron cleanup:")
    for entry in matches:
        print(f"  remove: {entry}")

    if not _prompt_yes_no("Apply this cron cleanup exactly as shown?", default=False):
        print("Cron cleanup skipped.")
        return matches

    filtered = [line for line in lines if line not in matches]
    new_crontab = "\n".join(filtered).strip()
    if new_crontab:
        new_crontab += "\n"

    update = subprocess.run(["crontab", "-"], input=new_crontab, text=True, capture_output=True, check=False)
    if update.returncode == 0:
        print("Removed matching entries from the current user's crontab.")
    else:
        print("Failed to update the current user's crontab.")
        if update.stderr:
            print(update.stderr.strip())
    return matches


def _inspect_related_systemd_units() -> list[str]:
    if shutil.which("systemctl") is None:
        return []

    result = _run_capture(["systemctl", "list-unit-files", "--type=service", "--type=timer", "--no-legend", "--no-pager"])
    if result.returncode != 0:
        return []

    matches: list[str] = []
    for line in result.stdout.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        unit_name = stripped.split()[0]
        lowered = unit_name.lower()
        if any(hint in lowered for hint in SYSTEMD_UNIT_HINTS):
            matches.append(unit_name)
    return sorted(set(matches))


def _print_systemd_cleanup_guidance(units: list[str]) -> None:
    if not units:
        return
    print("Found related systemd units or timers that may overlap:")
    for unit in units:
        print(f"  {unit}")
    print("Suggested cleanup command:")
    print("  sudo systemctl disable --now " + " ".join(units))
    print("If you also want to remove old unit files, inspect /etc/systemd/system and delete only the ones you recognize.")


def run_install(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Interactive installer for pi-probe-discord")
    parser.add_argument("--install-dir", default="/opt/pi-probe-discord")
    parser.add_argument("--output-dir", default=".")
    parser.add_argument("--venv-python", default="")
    parser.add_argument("--config-dir", default=str(DEFAULT_CONFIG_DIR))
    parser.add_argument("--data-dir", default=str(DEFAULT_DATA_DIR))
    parser.add_argument("--service-command", default="")
    parser.add_argument("--skip-systemd-generation", action="store_true")
    parser.add_argument("--package-mode", action="store_true")
    parser.add_argument("--systemd-override-dir", default="/etc/systemd/system")
    args = parser.parse_args(argv)

    install_dir = Path(args.install_dir)
    output_dir = Path(args.output_dir).resolve()
    venv_python = args.venv_python or f"{install_dir}/.venv/bin/python"
    service_command = args.service_command or f"{venv_python} {install_dir}/pihole_update_report.py"
    config_dir = Path(args.config_dir)
    data_dir = Path(args.data_dir)
    systemd_override_root = Path(args.systemd_override_dir)
    systemd_dir = output_dir / "generated-systemd"
    config_path = output_dir / DEFAULT_CONFIG_FILE.name
    target_config_path = config_dir / DEFAULT_CONFIG_FILE.name
    db_path = data_dir / DEFAULT_DB_PATH.name
    chart_path = data_dir / DEFAULT_CHART_PATH.name

    _inspect_and_clean_user_crontab()
    _print_systemd_cleanup_guidance(_inspect_related_systemd_units())

    webhook = _prompt_webhook("https://discord.com/api/webhooks/replace/this")
    speedtest_minutes = int(_prompt("Publish speedtest results every how many minutes?", str(DEFAULT_SPEEDTEST_MINUTES)))
    full_report_schedule = _validate_hhmm(_prompt("Daily full report time (24h HH:MM)", DEFAULT_FULL_REPORT_SCHEDULE))

    output_dir.mkdir(parents=True, exist_ok=True)
    config_path.write_text(
        ENV_TEMPLATE.format(
            webhook_url=webhook,
            db_path=db_path,
            chart_path=chart_path,
            speedtest_minutes=speedtest_minutes,
            full_report_schedule=full_report_schedule,
        ),
        encoding="utf-8",
    )
    os.chmod(config_path, 0o600)

    speedtest_override_rel = Path("pi-probe-discord-speedtest.timer.d/override.conf")
    full_override_rel = Path("pi-probe-discord-full.timer.d/override.conf")
    speedtest_override_target = systemd_override_root / speedtest_override_rel
    full_override_target = systemd_override_root / full_override_rel
    hh, mm = full_report_schedule.split(":")

    if not args.skip_systemd_generation:
        systemd_dir.mkdir(parents=True, exist_ok=True)
        (systemd_dir / "pi-probe-discord-speedtest.service").write_text(
            SERVICE_TEMPLATE.format(
                mode_label="periodic speed test",
                install_dir=install_dir,
                mode="speedtest-only",
                service_command=service_command,
            ),
            encoding="utf-8",
        )
        (systemd_dir / "pi-probe-discord-full.service").write_text(
            SERVICE_TEMPLATE.format(
                mode_label="full maintenance report",
                install_dir=install_dir,
                mode="full",
                service_command=service_command,
            ),
            encoding="utf-8",
        )
        (systemd_dir / "pi-probe-discord-speedtest.timer").write_text(
            TIMER_TEMPLATE.format(
                description="Run Pi Probe Discord speed tests periodically",
                schedule_line=f"OnActiveSec={speedtest_minutes}min\nOnUnitActiveSec={speedtest_minutes}min\nOnBootSec=10min",
                random_delay="5min",
                unit_name="pi-probe-discord-speedtest",
            ),
            encoding="utf-8",
        )
        (systemd_dir / "pi-probe-discord-full.timer").write_text(
            TIMER_TEMPLATE.format(
                description="Run Pi Probe Discord full maintenance report daily",
                schedule_line=f"OnCalendar=*-*-* {hh}:{mm}:00\nOnBootSec=20min",
                random_delay="15min",
                unit_name="pi-probe-discord-full",
            ),
            encoding="utf-8",
        )
    if args.package_mode:
        speedtest_override_target.parent.mkdir(parents=True, exist_ok=True)
        full_override_target.parent.mkdir(parents=True, exist_ok=True)
        speedtest_override_target.write_text(
            TIMER_OVERRIDE_TEMPLATE.format(
                on_boot="10min",
                on_active=f"{speedtest_minutes}min",
                schedule_line=f"OnUnitActiveSec={speedtest_minutes}min",
                random_delay="5min",
            ),
            encoding="utf-8",
        )
        full_override_target.write_text(
            TIMER_OVERRIDE_TEMPLATE.format(
                on_boot="20min",
                on_active="",
                schedule_line=f"OnCalendar=*-*-* {hh}:{mm}:00",
                random_delay="15min",
            ),
            encoding="utf-8",
        )

    print(f"Wrote config: {config_path}")
    print("Config permissions set to 600.")
    print("Target Debian-style layout:")
    print(f"  app dir: {install_dir}")
    print(f"  config dir: {config_dir}")
    print(f"  config file: {target_config_path}")
    print(f"  data dir: {data_dir}")
    print(f"  database: {db_path}")
    print(f"  chart: {chart_path}")
    print("Next steps:")
    if args.package_mode:
        print(f"1. Verify config at {target_config_path}")
        print(f"2. Timer overrides written to:")
        print(f"   {speedtest_override_target}")
        print(f"   {full_override_target}")
        print("3. Run: sudo systemctl daemon-reload")
        print("4. Run: sudo systemctl enable --now pi-probe-discord-speedtest.timer pi-probe-discord-full.timer")
        print("5. Re-run sudo pi-probe-discord-install any time you want to change the schedule.")
    else:
        print(f"1. Copy this project to {install_dir}")
        print(f"2. Create directories: sudo mkdir -p {config_dir} {data_dir}")
        print(f"3. Copy {config_path.name} into {target_config_path}")
        print(f"4. Set config ownership and mode: sudo chown root:root {target_config_path} && sudo chmod 600 {target_config_path}")
        if args.skip_systemd_generation:
            print("5. Systemd unit generation was skipped.")
            print("6. Use the packaged units already installed on the system, then run:")
            print("   sudo systemctl daemon-reload")
            print("   sudo systemctl enable --now pi-probe-discord-speedtest.timer pi-probe-discord-full.timer")
        else:
            print(f"Wrote systemd units: {systemd_dir}")
            print(f"5. Copy generated systemd unit files from {systemd_dir} into /etc/systemd/system/")
            print("6. Run: sudo systemctl daemon-reload")
            print("7. Run: sudo systemctl enable --now pi-probe-discord-speedtest.timer pi-probe-discord-full.timer")
    print(f"Generated services use command: {service_command}")
    return 0
